[build]
  command = "npm exec --yes --package=pnpm@10.25.0 -- pnpm install --frozen-lockfile && npm exec --yes --package=pnpm@10.25.0 -- pnpm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
